---
resources:
  - name: capi-ci
    type: git
    source:
      branch: main
      uri: https://github.com/cloudfoundry/capi-ci

  - name: start-of-work-day
    type: time
    icon: weather-sunset-up
    source:
      location: America/Los_Angeles
      start: 8:00 AM
      stop: 8:15 AM
      days: [Monday, Tuesday, Wednesday, Thursday, Friday]

  - name: end-of-work-day
    type: time
    icon: weather-night
    source:
      location: America/Los_Angeles
      start: 6:15 PM
      stop: 6:30 PM
      days: [Monday, Tuesday, Wednesday, Thursday, Friday]

  - name: end-of-work-week
    type: time
    icon: surfing
    source:
      location: America/Los_Angeles
      start: 6:15 PM
      stop: 6:45 PM
      days: [Friday]

jobs:
  - name: startup-capi-ws-1
    plan:
      - get: capi-ci
      - get: start-of-work-day
        trigger: true
      - task: startup
        file: capi-ci/ci/workstation-scheduler/startup-ws.yml
        params:
          GCP_VM_NAME: capi-ws-1
          GCP_VM_ZONE: us-central1-a
          GCP_SERVICE_ACCOUNT_KEY: ((arya_gcp_json_key))

  - name: startup-capi-ws-2
    plan:
      - get: capi-ci
      - get: start-of-work-day
        trigger: true
      - task: startup
        file: capi-ci/ci/workstation-scheduler/startup-ws.yml
        params:
          GCP_VM_NAME: capi-ws-2
          GCP_VM_ZONE: us-central1-a
          GCP_SERVICE_ACCOUNT_KEY: ((arya_gcp_json_key))

  - name: startup-capi-ws-3
    plan:
      - get: capi-ci
      - get: start-of-work-day
        trigger: true
      - task: startup
        file: capi-ci/ci/workstation-scheduler/startup-ws.yml
        params:
          GCP_VM_NAME: capi-ws-3
          GCP_VM_ZONE: us-central1-a
          GCP_SERVICE_ACCOUNT_KEY: ((arya_gcp_json_key))

  - name: startup-capi-ws-4
    plan:
      - get: capi-ci
      - get: start-of-work-day
        trigger: true
      - task: startup
        file: capi-ci/ci/workstation-scheduler/startup-ws.yml
        params:
          GCP_VM_NAME: capi-ws-4
          GCP_VM_ZONE: us-central1-a
          GCP_SERVICE_ACCOUNT_KEY: ((arya_gcp_json_key))

  - name: startup-capi-ws-5
    plan:
      - get: capi-ci
      - get: start-of-work-day
        trigger: true
      - task: startup
        file: capi-ci/ci/workstation-scheduler/startup-ws.yml
        params:
          GCP_VM_NAME: capi-ws-5
          GCP_VM_ZONE: us-central1-a
          GCP_SERVICE_ACCOUNT_KEY: ((arya_gcp_json_key))

  - name: startup-capi-ws-6
    plan:
      - get: capi-ci
      - get: start-of-work-day
        trigger: true
      - task: startup
        file: capi-ci/ci/workstation-scheduler/startup-ws.yml
        params:
          GCP_VM_NAME: capi-ws-6
          GCP_VM_ZONE: us-central1-a
          GCP_SERVICE_ACCOUNT_KEY: ((arya_gcp_json_key))


  - name: shutdown-capi-ws-1
    plan:
      - get: capi-ci
      - get: end-of-work-day
        trigger: true
      - task: shutdown
        file: capi-ci/ci/workstation-scheduler/shutdown-ws.yml
        params:
          GCP_VM_NAME: capi-ws-1
          GCP_VM_ZONE: us-central1-a
          GCP_SERVICE_ACCOUNT_KEY: ((arya_gcp_json_key))

  - name: shutdown-capi-ws-2
    plan:
      - get: capi-ci
      - get: end-of-work-day
        trigger: true
      - task: shutdown
        file: capi-ci/ci/workstation-scheduler/shutdown-ws.yml
        params:
          GCP_VM_NAME: capi-ws-2
          GCP_VM_ZONE: us-central1-a
          GCP_SERVICE_ACCOUNT_KEY: ((arya_gcp_json_key))

  - name: shutdown-capi-ws-3
    plan:
      - get: capi-ci
      - get: end-of-work-day
        trigger: true
      - task: shutdown
        file: capi-ci/ci/workstation-scheduler/shutdown-ws.yml
        params:
          GCP_VM_NAME: capi-ws-3
          GCP_VM_ZONE: us-central1-a
          GCP_SERVICE_ACCOUNT_KEY: ((arya_gcp_json_key))

  - name: shutdown-capi-ws-4
    plan:
      - get: capi-ci
      - get: end-of-work-day
        trigger: true
      - task: shutdown
        file: capi-ci/ci/workstation-scheduler/shutdown-ws.yml
        params:
          GCP_VM_NAME: capi-ws-4
          GCP_VM_ZONE: us-central1-a
          GCP_SERVICE_ACCOUNT_KEY: ((arya_gcp_json_key))

  - name: shutdown-capi-ws-5
    plan:
      - get: capi-ci
      - get: end-of-work-day
        trigger: true
      - task: shutdown
        file: capi-ci/ci/workstation-scheduler/shutdown-ws.yml
        params:
          GCP_VM_NAME: capi-ws-5
          GCP_VM_ZONE: us-central1-a
          GCP_SERVICE_ACCOUNT_KEY: ((arya_gcp_json_key))

  - name: shutdown-capi-ws-6
    plan:
      - get: capi-ci
      - get: end-of-work-day
        trigger: true
      - task: shutdown
        file: capi-ci/ci/workstation-scheduler/shutdown-ws.yml
        params:
          GCP_VM_NAME: capi-ws-6
          GCP_VM_ZONE: us-central1-a
          GCP_SERVICE_ACCOUNT_KEY: ((arya_gcp_json_key))

  - name: shutdown-workstations
    plan:
      - get: capi-ci
      - get: end-of-work-week
        trigger: true
      - task: shutdown-all
        file: capi-ci/ci/workstation-scheduler/shutdown-all-ws.yml
        params:
          GCP_VM_ZONE: us-central1-a
          GCP_SERVICE_ACCOUNT_KEY: ((arya_gcp_json_key))

