---
resources:
  - name: daily
    type: time
    icon: clock-outline
    source:
      interval: 24h
  - name: capi-ci-private
    type: git
    icon: git
    source:
      uri: https://github.com/cloudfoundry/capi-ci-private.git
      branch: main
      username: ((ari-wg-gitbot-username))
      password: ((ari-wg-gitbot-token))
  - name: runtime-ci
    type: git
    icon: git
    source:
      uri: https://github.com/cloudfoundry/runtime-ci.git
      branch: main
jobs:
  - name: validate-certs
    serial: true
    public: true
    plan:
      - in_parallel:
          - get: daily
            trigger: true
          - get: capi-ci-private
            trigger: true
          - get: runtime-ci
            trigger: true
      - task: validate-certs
        file: runtime-ci/tasks/check-certs/task.yml
        input_mapping:
          relint-envs: capi-ci-private
        params:
          DAYS_LEFT_THRESHOLD: 16
          PATH_TO_VERIFY: relint-envs
          PATHS_TO_IGNORE:
            - TO_BE_DELETED/arya/certs/load-balancer
            - TO_BE_DELETED/ci-green/vars
            - TO_BE_DELETED/elsa/self-signed-certs/load-balancer
            - TO_BE_DELETED/gabrielle-postgres/certs/load-balancer
            - TO_BE_DELETED/kiki/certs/load-balancer
            - TO_BE_DELETED/leia-azure-storage/certs/load-balancer
            - TO_BE_DELETED/mulan/certs/load-balancer
            - TO_BE_DELETED/rey-gcs-storage/certs/load-balancer
            - TO_BE_DELETED/ripley/certs/load-balancer
            - TO_BE_DELETED/rose/certs
            - TO_BE_DELETED/rose/vars
            - TO_BE_DELETED/xena-mysql/certs/load-balancer
