---
resources:
  - name: daily
    type: time
    icon: clock-outline
    source:
      interval: 24h
  - name: capi-ci-private
    type: git
    icon: git
    source:
      uri: https://github.com/cloudfoundry/capi-ci-private.git
      branch: main
      username: ((ari-wg-gitbot-username))
      password: ((ari-wg-gitbot-token))
  - name: runtime-ci
    type: git
    icon: git
    source:
      uri: https://github.com/cloudfoundry/runtime-ci.git
      branch: main
jobs:
  - name: validate-certs
    serial: true
    public: true
    plan:
      - in_parallel:
          - get: daily
            trigger: true
          - get: capi-ci-private
            trigger: true
          - get: runtime-ci
            trigger: true
      - task: validate-certs
        file: runtime-ci/tasks/check-certs/task.yml
        input_mapping:
          relint-envs: capi-ci-private
        params:
          DAYS_LEFT_THRESHOLD: 16
          PATH_TO_VERIFY: relint-envs
